/** @type {import('tailwindcss').Config} */
// Design tokens ported verbatim from the Stitch "Silver Variant" screen so all
// the original utility classes resolve identically.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#0d1c2d',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b4cbce',
        'on-tertiary-container': '#617083',
        'inverse-on-surface': '#f0f1f1',
        'on-primary-container': '#5d7275',
        'on-tertiary-fixed-variant': '#39485a',
        'on-secondary-container': '#626567',
        'tertiary-fixed-dim': '#b9c8de',
        'surface-dim': '#dadada',
        secondary: '#5c5f61',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#444749',
        'on-error-container': '#93000a',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        tertiary: '#516072',
        'surface-container-low': '#f3f3f4',
        outline: '#727879',
        'tertiary-container': '#edf3ff',
        'inverse-primary': '#b4cbce',
        'primary-fixed': '#d0e7ea',
        'on-primary-fixed-variant': '#364a4d',
        primary: '#4d6265',
        'on-secondary-fixed': '#191c1e',
        'on-primary-fixed': '#091f21',
        'surface-tint': '#4d6265',
        'secondary-container': '#e0e3e5',
        'on-surface-variant': '#424849',
        'on-secondary': '#ffffff',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-bright': '#f9f9f9',
        'on-error': '#ffffff',
        'outline-variant': '#c2c7c8',
        'inverse-surface': '#2f3131',
        'secondary-fixed-dim': '#c4c7c9',
        'on-surface': '#1a1c1c',
        'surface-container-highest': '#e2e2e2',
        'secondary-fixed': '#e0e3e5',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#d4e4fa',
        'primary-container': '#e0f7fa',
        background: '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        surface: '#f9f9f9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'label-sm': ['Sora', 'sans-serif'],
        'label-md': ['Sora', 'sans-serif'],
        'body-lg': ['Sora', 'sans-serif'],
        'body-md': ['Sora', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-xl-mobile': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
